### ISSUE TITLE
SQL error i navngivenvej

### ISSUE THREAD

**Issue by cfischer00** [SDFIdk/gsearch#103]
I forbindelse med oprydning foretaget af @Nobralyra er udkommentering af ulovlig kode fjernet.

Det betyder at SQL'en ikke længere er valid. Præsentation for navngiven vej skal rettes.

Det er denne linje:

https://github.com/SDFIdk/gsearch/blob/a166485cf4d2b400a3d783c95620c1c524ddae95/db/seed/030_api_navngivenvej.sql#L39

Som blev ændret i dette commit: https://github.com/SDFIdk/gsearch/commit/8554aee01f4b55f88f5ee582b1c35fff31ea80f6

Den sidste del skal fjernes (og erstattes af noget præsentation for postnumre.

**Comment by Nobralyra** [comment]
Skal hele `|| '(' || v.postnummer[1] || ' - ' || v.postnummer[-1] || ')'` bare fjernes, så der bliver til 
`SELECT v.vejnavn AS praesentation,`?

**Comment by cfischer00** [comment]
Ja, men kan du ikke lige ringe til mig på 9132 6942
