### ISSUE TITLE
Til brugerdokumentationen

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#104]
Til brugerdokumentationen @cfischer00 skriver, vil følgende fra [PR 102 ](https://github.com/SDFIdk/gsearch/pull/102) som @bjornharrtell lavede, være gode at gøre brugeren opmærksom på.

- Værdien angivet i filter query parameter, skal være URL encoded, for at når der bruges wildcard character som % fx i en `like` søgning, at så bliver SQL til databasen korrekt.
- Filter query parameteren kan ikke håndtere numerics kolonner i databasen, men da næsten alle kolonner i de forskellige tabeller i databasen er `text`, vil det nok ikke være et problem.
- Geometrier clienten kan spørge med kan kun være i crs `25832`.

**Comment by JesperKock** [comment]
Filter query parameteren skal være tekst mangler.
Filter skal have en overskrift
