### ISSUE TITLE
Søgning i matrikelnummer tager for lang tid

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#106]
Søgning i matrikelnummer rammer time out på 10 sekunder: `https://api.dataforsyningen.dk/gsearch_test/v1.0/search?q=s&resources=matrikelnummer`.

Samme søgning i databasen tog 31 sekunder, så er noget optimering der skal laves der. Det skal nok den samme optimering som `adresse`, `husnummer`, `navngivenvej` og `stednavn` har.

**Comment by JesperKock** [comment]
Fixed with #0b88f6c19d13bfb12a5d443bef41015110b30b32
