### ISSUE TITLE
Tilføjelse af postnummer og kommunenavn til søgestrengen i relavante resourcer

### ISSUE THREAD

**Issue by Gebuz** [SDFIdk/gsearch#111]
f.eks. hvis jeg vil søge på rentemestervej i københavn og ikke den i hillerød. Hvis jeg søger på rentemestervej 2400 eller rentemestervej københavn får jeg ikke nogen resultater.

Ville være smart hvis man på resourcen husnummer kunne søge på noget i formattet der matcher `adgangsadressebetegnelse`, f.eks. `Rentemestervej 2, 2400 København NV` og tilsvarende på resourcen adresse i formattet der matcher `adressebetegnelse`, f.eks. `Rentemestervej 24, st. th, 2400 København NV`

**Comment by JesperKock** [comment]
Du kan få hvad du efterspørger ved at bruge filter funktionen, her er et eksempel på en adresse søgningen med husnummer der filtrer for postnummer 2400:

`https://api.dataforsyningen.dk/gsearch_test/v1.0/search?q=Rentemestervej%202&resources=adresse&filter=postnummer%3D'2400'`

**Comment by Gebuz** [comment]
resource -> søgefelter
`husnummer`->`adgangsadressebetegnelse`
`adresse`->`adressebetegnelse`

**Comment by JesperKock** [comment]
Har forbindelse til #132 da visningsteksten skal stemme overens med hvad brugeren kan søge i.

**Comment by JesperKock** [comment]
Man kan på nuværende tidspunkt søge med både postnummer og postnummernavn (kommune) i følgende resourcer:
- adresse
- husnummer
- navngivenvej

Er der andre resourcer det giver mening at implementer dette på?

**Comment by iamfrank** [comment]
@JesperKock Har testet med adresse, husnummer, navngivenvej. Virker umiddelbart fint.

Ville det ikke give mening at kunne søge i resourcen kommune med postnummer?

**Comment by JesperKock** [comment]
@iamfrank Det burde man kunne.

**Comment by iamfrank** [comment]
Jeg prøver at finde "Roskilde kommune" ved at søge på "4000":
`https://api.dataforsyningen.dk/gsearch_test/v1.0/kommune?token=fd44f26ab5701c01ca9f570e507fe9ab&q=4000&limit=10` returnerer 0 results.

**Comment by iamfrank** [comment]
Ved heller ikke, om det er supervigtigt at kunne. Det virkede relevant.

**Comment by JesperKock** [comment]
@iamfrank Det giver godt mening at man burde kunne det.

**Comment by Nobralyra** [comment]
> nuværende

Man kan det samme i gsearch.

Kommune søgning Roskilde
![image](https://user-images.githubusercontent.com/48592380/212892294-0580d891-2895-4537-842d-2eadd97f8fca.png)

Postnummer søgning 4000
![image](https://user-images.githubusercontent.com/48592380/212892351-5b19636d-ab2c-4a7c-a062-83acae2807d5.png)

**Comment by Nobralyra** [comment]
> @JesperKock Har testet med adresse, husnummer, navngivenvej. Virker umiddelbart fint.
> 
> Ville det ikke give mening at kunne søge i resourcen kommune med postnummer?

Dette giver ikke umiddelbart mening, da kommune ikke har data om hvilke postnumre den er i kommunen.
