### ISSUE TITLE
DAR - forslag til ændring af "name"

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#113]
Mail Karen 8.12

**Name husnummer  skal ændres til husnummertekst**
https://docs.dataforsyningen.dk/#tocS_husnummer
![image](https://user-images.githubusercontent.com/72433485/205889613-0fcb85af-990e-4047-b11c-34ca9d566053.png)

**Name postdistrikt skal ændres til postnummernavn**
https://docs.dataforsyningen.dk/#tocS_postdistrikt
![image](https://user-images.githubusercontent.com/72433485/205889486-5f160b36-9441-4f5c-ac25-fe229464aee1.png)

**Comment by JesperKock** [comment]
Name postdistrikt is duplicate from  #117
