### ISSUE TITLE
Foreslået rækkefølge i dokumentationen

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#114]
Foreslået rækkefølge i dokumentationen:

Husnummer
Adresse
Navngivenvej
Postnummernavn
Sogneinddeling
Kommuneinddeling
Regionsinddeling
Retskreds
Politikreds
Opstillingskreds
Matrikel 

t.o. link dokumentation
http://docs.dataforsyningen.dk/#gsearch-dokumentation

 
![image](https://user-images.githubusercontent.com/72433485/205882598-bec02cf0-fbf2-4acd-bce3-c7cccbaf2587.png)

http://docs.dataforsyningen.dk/#gsearch

 
![image](https://user-images.githubusercontent.com/72433485/205882653-4f5674b0-6859-4e6c-9c59-b281d03bfc1a.png)

**Comment by JesperKock** [comment]
Alfabetisk rækkefølge
