### ISSUE TITLE
Specifikke søgninger i navngivenvej fejler (Troldebuen fejlen)

### ISSUE THREAD

**Issue by JesperKock** [SDFIdk/gsearch#119]
Søgninger som Troldebuen og Christianø fejler i resources navngivenvej.

Fejlen kommer måske af manglende geometri for nogle veje under navngivenvej.

**Comment by AnnetteSDFE** [comment]
jeg beder lone og margit teste vedr adresse

**Comment by AnnetteSDFE** [comment]
testet ok af lone (mail 10.1)
