### ISSUE TITLE
Begrænsning af input på flere resourcer bliver delt

### ISSUE THREAD

**Issue by Gebuz** [SDFIdk/gsearch#121]
Nogle resourcer har begrænsninger i input. Hvis man søgner på flere resourcer samtidigt vil denne begrænsning stoppe søgningen på alle resourcerne. F.eks. hvis man søger på "a 0 a" vil `kommune` resourcen returnere bad input. Det gør den ikke hvis man søger på `navngivenvej`. Men hvis jeg søger på begge resourcer samtidigt får man også en bad input. Det burde vel ikke begrænse `navngivenvej` søgningen at det er et bad input for `kommune` søgningen.

**Comment by JesperKock** [comment]
Dette er et issue for resourcerne:
- Kommune
- Postdistrik
- Matrikelnummer
