### ISSUE TITLE
Request med specifik CRS

### ISSUE THREAD

**Issue by iamfrank** [SDFIdk/gsearch#122]
Det ville være meget anvendeligt, hvis man kunne requeste data fra gsearch og bede om at få evt. koordinater ud i en anden projektion end EPSG:25832 - f.eks. WGS84.

Så kunne response data bruges uden videre i f.eks. LeafletJS.

**Comment by baffioso** [comment]
Hvad er status på denne?

**Comment by JesperKock** [comment]
Implemented in: https://github.com/SDFIdk/gsearch/releases/tag/v2.0.0
