### ISSUE TITLE
Pick a language :)

### ISSUE THREAD

**Issue by iamfrank** [SDFIdk/gsearch#123]
Jeg staver konstant forkert, når jeg skal behandle data fra en gsearch response. 

Var det nu `geometry.coordinates` eller `geometri.koordinater`?
... det var `geometri.coordinates`. 

Det ville være nemmere at huske, hvis sprogvalget var mere konsistent.

**Comment by JesperKock** [comment]
![Screenshot from 2022-12-15 11-07-15](https://user-images.githubusercontent.com/100782921/207831536-21a5e188-6da9-46d5-9ea6-7c83d1c70f6b.png)
`https://api.dataforsyningen.dk/rest/gsearch/v1.0/search?q=amalienborg&resources=husnummer&token={REMOVED}`

Vi kan se at coordinates og multipoint er på engelsk men ellers bruges dansk. Disse kan ikke ændres særlig nemt da de bliver sat af nogle biblioteker der bliver brugt.

Hvis du har andre eksempler så vil vi gerne have dem.
