### ISSUE TITLE
Dokumentationen skal specificere, hvor geometrierne der returneres hentes fra.

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#127]
Om det er fra DAR, GeoDanmark eller hvor de kommer originalt fra.
Reference geometri eller simplificeret.

**Comment by AnnetteSDFE** [comment]
er det på de enkelte ressourcer, at description kan/skal tilføjes med oplysning om datakilde?
ex. for adresse?
http://load225.kmsext.dk:6400/#tocS_adresse

**Comment by AnnetteSDFE** [comment]
er ikke specificeret yderligere
