### ISSUE TITLE
Tilføjelse:  Eksempler på inkonsistens i ”efterteksterne” i stednavne

### ISSUE THREAD

**Issue by JesperKock** [SDFIdk/gsearch#128]
H.C. Andersen Golf (Bogense)
Kølleeng (Naturareal/Mark)
Dade (Bebyggelse/Bebyggelse) 
Kaas (By i Pandrup)
Den uendelige Bro (Vej/Bro)
Planetstien (Vej/Sti)
Jesperhus Blomsterpark (Nykøbing M)
Blomstergården (Blomsterpark i Tjele)
Povlskirke (Kirke i Nexø)
Rødovre Kirke (Rødovre)

Ved golfbaner mangler topografitypen, ved naturarealer mangler lokationen, ved nogle typer bebyggelser mangler lokationen, men featuretypen står to gange, ved featuretypen Vej er der både featuretype og topografitype, men ingen lokation. Nogle objekter med topografitypen ’blomsterpark’ får vist typen, andre ikke. 

Der skal altid være en **topografitypen** og **lokation**.

**Comment by JesperKock** [comment]
Skal vises som f.eks. (Blomsterpark i Tjele)

**Comment by AnnetteSDFE** [comment]
Elvis foreslår, at det også skal være muligt at søge i teksten som vises i parantes ex. Blomstergården (Blomsterpark i Tjele).
i dag får man ikke et resultat hvis man søger "blomster t"

**Comment by AnnetteSDFE** [comment]
@AnetteKlinker har du kommentarer til beskrivelsen ovenfor?
ændringen består i, at der for ressourcen stednavne altid tilføjes lokation og typografitype i parantes.
desuden foreslår ITU, at det også skal være muligt at søge i "lokation" og "typografitype".

**Comment by AnnetteSDFE** [comment]
løst i vers 1.1.0
