### ISSUE TITLE
Ændring fra resourcer til multiple endpoints

### ISSUE THREAD

**Issue by JesperKock** [SDFIdk/gsearch#129]
Eksempler med søgestreng 'amalienborg',

`https://api.dataforsyningen.dk/rest/gsearch/v1.0/search?q=amalienborg&resources=husnummer`

ville f.eks. bliver til:

`https://api.dataforsyningen.dk/rest/gsearch/v1.0/husnummer?q=amalienborg`
`https://api.dataforsyningen.dk/rest/gsearch/v1.0/husnummer?s=amalienborg`
`https://api.dataforsyningen.dk/rest/gsearch/v1.0/husnummer/amalienborg`

**Comment by JesperKock** [comment]
Er det okay at lave flere kald og få flere JSON responses for frontend udviklere?

**Comment by iamfrank** [comment]
@JesperKock Det kommer an på ...

Hvis man kører man en gammel HTTP-protokol, så er flere forespørgsler = dårligere performance, fordi man skal lave handshake med serveren for hver eneste request. Moderne HTTP-protokoller klarer det lidt bedre.

Jeg har altid foretrukket "chunky, not chatty" udveksling af data mellem server og klient, men det er en afvejning. 
Man vil heller ikke have en masse data, man ikke skal bruge til noget, hvilket tit er det der sker, når man beder om et "chunky" response fra de kære backend-udviklere.

Indtil videre ser det ud til, at vi oftest bruger Gsearch i kontekster, hvor vi har gang i flere resourcer på samme tid. Så jeg vil umiddelbart tænke det var et tab at fjerne muligheden for at spørge efter flere resource i samme request.

**Comment by iamfrank** [comment]
Har I overvejet et GraphQL API i stedet?

**Comment by Nobralyra** [comment]
Fordele ved opdeling af endpoints er:
1. Bedre info omkring antallet af kald og svartider.
2. Bedre implementering af count
3. Ikke bundet af det langsommeste kald, hvis man requester flere resourcer på en gang.

**Comment by iamfrank** [comment]
@AnnetteSDFE Jeg ser, at jeg er assigned til dette issue. Hvad skal der ske? Implementering i GSearch-UI og lukning af issue?

**Comment by AnnetteSDFE** [comment]
@iamfrank Jesper tager lige fat i dag - Annette

**Comment by iamfrank** [comment]
Multiple endpoints er implementeret i GSearch-UI v0.8

**Comment by DocDemar** [comment]
> Multiple endpoints er implementeret i GSearch-UI v0.8

ville det give mening at have en default ressource slået til
Hvis ikke man klikke på en af ressourcerne giver søgningen ikke noget resultat
Feedback til brugeren om at slå en ressource til kunne også være en mulighed

**Comment by Gebuz** [comment]
Det gør den allerede på test siden, den fejler bare lige nu pga. postdistrikt skal opdateres til postnummer

**Comment by JesperKock** [comment]
Gsearch UI issue moved:
https://github.com/SDFIdk/gsearch-ui/issues/28

**Comment by Gebuz** [comment]
Det er fixet nu

**Comment by JesperKock** [comment]
@AnnetteSDFE Gsearch-UI skulle bruge de nye endpoints, så det virker.

**Comment by iamfrank** [comment]
Der er en implemtation på https://test11.dataforsyningen.dk, som kan testes om lidt (stednavne og navngivenvej).

**Comment by AnnetteSDFE** [comment]
@AnetteKlinker kan I teste her https://test11.dataforsyningen.dk/ vedr. #125
