### ISSUE TITLE
'Standard' geometri

### ISSUE THREAD

**Issue by JesperKock** [SDFIdk/gsearch#130]
Nogle ressourcer har mere end en geometri.

Alle ressourcer burde have en 'standard' geometri der hedder geometri for at gøre det lettere at vælge.

**Comment by JesperKock** [comment]
Dette er for resourcerne husnummer og adresse.

Forslag er at omdøbe adgangspunkt_geometri til geometri

**Comment by AnnetteSDFE** [comment]
skrevet til karen og margit dd

**Comment by AnnetteSDFE** [comment]
rykket Karen og Margit dd

**Comment by AnnetteSDFE** [comment]
svar fra lone pr mail dd

I produktet ”Danmarks adresser og vejnavne” har vi 3 objekter med geometri ”adgangspunkt”, ”vejpunkt” og ”navngivenvej”.
Hvordan vil I repræsentere geometrien for navngivenvej, vil denne også alene hedde ”geometri”? Og er det afklaret hvilke geometrier der udstilles for navngivenvej?
Hvor stort et ”problem” er det at beholde navnet ”adgangspunkt_geometri”?

**Comment by AnnetteSDFE** [comment]
for ressourcerne adresse og husnummer skal adgangspunkt_geometri omdøbes til geometri.
