### ISSUE TITLE
navngivenvej - tilføj `postnummer` + `postnummernavn` til `visningstekst`

### ISSUE THREAD

**Issue by seskildsen** [SDFIdk/gsearch#132]
På navngivenvej tilføjes postnumre og postnummernavne til visningstekst.

**Comment by Nobralyra** [comment]
I navngivenvej kan rækker have:

1. Et vejnavn har et postnumre og et postnummernavne.
2. Et vejnavn har flere postnumre og et postnummernavne.
3. Et vejnavn har flere postnumre og flere postnummernavne.

**Comment by AnnetteSDFE** [comment]
afventer hvordan problemet kan løses i div applikationer

**Comment by seskildsen** [comment]
@DKbest 

Det er ikke helt så simpelt som man kunne tro med at tilføje `postnummer` + `postnummernavn` til  `visningstekst` for `navngivenvej`, da der kan være flere postnumre og postnummernavne for hvert vejnavn, og hvilke skal så stå først og `visniningstekst` værdien kan ende med at være meget lang. 

> I navngivenvej kan rækker have:
> 
> 1. Et vejnavn har et postnumre og et postnummernavne.
> 2. Et vejnavn har flere postnumre og et postnummernavne.
> 3. Et vejnavn har flere postnumre og flere postnummernavne.

**Comment by DKbest** [comment]
Hmmm...ja det kan jeg godt se - @Gebuz er det mon bedre/nemmere at vi håndterer det i frontend på en eller anden måde? 
![image](https://github.com/SDFIdk/gsearch/assets/79503214/e6a04d2f-1f19-4b8b-b8bf-ba638cc55f57)

**Comment by JesperKock** [comment]
Implemented in: https://github.com/SDFIdk/gsearch/releases/tag/v2.0.0
