### ISSUE TITLE
Implementering - visning af uofficielle navne

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#134]
der kan fremsøges steder, der alene er registreret med et uofficielt navn:

![image](https://user-images.githubusercontent.com/72433485/207886738-72037cfa-8019-4e18-bdc8-6d342a6ec0cf.png)

**Comment by JesperKock** [comment]
Dette issue kommer af uofficielle vejkryds ikke er tilføjet i Gsearch.

**Comment by AnetteKlinker** [comment]
Så vidt jeg kan se, er det alle uofficielle navne, hvor der ikke er registreret et officielt navn - ikke kun vejkryds.

**Comment by JesperKock** [comment]
Problemet burde være for alle stednavne. Det er dog ikke skubbet til produktion.

**Comment by AnnetteSDFE** [comment]
som jeg forstår kan anette k ikke godkende testen. jeg flytter sagen til prioriteret - vi kan evt tage et møde med Anette K

**Comment by AnnetteSDFE** [comment]
testet dd - ok kan lukkes
