### ISSUE TITLE
Stednavne med én karakter skal kunne fremsøges - eks. Å

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#135]
Anette K: 
I #27 er det løst, at stednavnet ”Ø” kan fremsøges; af en eller anden grund **gælder det ikke for stednavnet ”Å”**

**Comment by Nobralyra** [comment]
Jeg kan ikke fremsøge med hverken stort ”Ø” eller stort ”Å”, men med små bogstaver kan jeg godt.

**Comment by AnnetteSDFE** [comment]
anette vil du teste denne?

**Comment by Nobralyra** [comment]
Det er ikke lagt i test og prod endnu. Kun på vores testtest database.

**Comment by AnnetteSDFE** [comment]
testet dd - Å er løst ift at søge på én karakter
