### ISSUE TITLE
præcis skrivemåde af stednavne

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#136]
Anette K: (stednavne)
Derudover vil det være meget mere brugervenligt, hvis man ikke behøver at kende den præcise skrivemåde, altså om der er blanktegn eller ej imellem delene af et sammensat navn. 

Fx skal man vide, at Brøndby Hallen skrives i to ord, eller også skal man være klar over, at man kan stoppe med at skrive efter ’Brøndby’.  

Der skelnes ikke mellem blanktegn og ’-’, så man får sit resultat ligegyldigt om man bruger det ene eller andet (fx Valby Hallen eller Valby-Hallen, men ikke Valbyhallen)

**Comment by Nobralyra** [comment]
Fixed in: https://github.com/SDFIdk/gsearch/commit/bded125ec35d1e396f644cccb88909e1a5797dbc

**Comment by AnnetteSDFE** [comment]
Beder Anette K om at teste
