### ISSUE TITLE
DUBLET stednavne - forskel i (eftertekst) i søgeresultaterne

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#137]
Anette K .
Eksempler på **inkonsistens i ”efterteksterne**”:

H.C. Andersen Golf (Bogense)
Kølleeng (Naturareal/Mark)
Dade (Bebyggelse/Bebyggelse) 
Kaas (By i Pandrup)
Den uendelige Bro (Vej/Bro)
Planetstien (Vej/Sti)
Jesperhus Blomsterpark (Nykøbing M)
Blomstergården (Blomsterpark i Tjele)
Povlskirke (Kirke i Nexø)
Rødovre Kirke (Rødovre)

Ved golfbaner mangler topografitypen, ved naturarealer mangler lokationen, ved nogle typer bebyggelser mangler lokationen, men featuretypen står to gange, ved featuretypen Vej er der både featuretype og topografitype, men ingen lokation. Nogle objekter med topografitypen ’blomsterpark’ får vist typen, andre ikke. 

Hvis jeg kan vælge, vil jeg foretrække, at der **altid står topografitype**n, også selv om det i nogle tilfælde bliver dobbelt. Jeg tror, det forvirrer mindst. 
Desuden skal der **altid være en lokation**.

**Comment by elvios** [comment]
@annetteSDFE finder lige ud af hvad vi egentlig gerne vil have inde i parenteserne.

**Comment by AnnetteSDFE** [comment]
@Nobralyra
den oprindelige sag er her - og er åben https://github.com/SDFIdk/gsearch/issues/128
skal vi lukke denne og fortsætte med sag 128

**Comment by AnnetteSDFE** [comment]
lukkes efter aftale med Signe og køres videre i 128
