### ISSUE TITLE
Fjerne rang1 og rang2 fra parameter

### ISSUE THREAD

**Issue by JesperKock** [SDFIdk/gsearch#140]
Fra: https://github.com/SDFIdk/gsearch/blob/main/doc/NOTES%20in%20TEST%20of%20GSearch.md

rang1 og rang2 har ingen beskrivelser i dokumentationen og er ikke relavent data for brugere af api'en.

**Comment by Nobralyra** [comment]
Kan rang1 og rang2 give mening i forhold til, hvorfor et resultat rangerer højere?

**Comment by JesperKock** [comment]
Fixed with fed79f3afed0e39a847c9b64a10029c1e17acaa5

**Comment by AnnetteSDFE** [comment]
@JesperKock hvem kan teste denne? er det Anette K?

**Comment by JesperKock** [comment]
Vi har testet den.
