### ISSUE TITLE
geometri - beskrivelse

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#142]
slet "i valgt koordinatsystem" i beskrivelsen for alle ressourcerne

**Comment by AnnetteSDFE** [comment]
hvor kan det testes?

**Comment by AnnetteSDFE** [comment]
fremgår stadig her
http://load225.kmsext.dk:6400/#gsearch-gsearch

**Comment by Nobralyra** [comment]
Burde ikke længe fremgå på dokumentationssiden.

**Comment by AnnetteSDFE** [comment]
testet ok
