### ISSUE TITLE
Fix error message fra ConnectionException

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#144]
Giv en anden fejlbesked.

**Comment by Nobralyra** [comment]
Fixes: https://github.com/SDFIdk/gsearch/commit/59f24d4e32bdc885fb696acf17749f59dd01b296

**Comment by AnnetteSDFE** [comment]
hvad kan jeg teste her?

**Comment by Nobralyra** [comment]
Det har du ikke mulighed for at teste.
