### ISSUE TITLE
Nogle kald er så langsomme at de når timeout

### ISSUE THREAD

**Issue by Gebuz** [SDFIdk/gsearch#150]
f.eks. 
`https://api.dataforsyningen.dk/gsearch_test/v1.0/adresse?q=fred`
`https://api.dataforsyningen.dk/gsearch_test/v1.0/adresse?q=frede`
`https://api.dataforsyningen.dk/gsearch_test/v1.0/adresse?q=freder`
Det kan være at det er udvidelsen med søgning med hus nr, post nr. og kommune der er årsag?

**Comment by Nobralyra** [comment]
Fixed in: https://github.com/SDFIdk/gsearch/commit/cac9f16d017273557bb2723987a84d9658710c62
