### ISSUE TITLE
Kommune søgning

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#151]
Hvis man tilføjer `kommune` til en søgning efter en kommune fx. Roskilde (som Roskilde K), så finder man ingen resultater, da textsearchable ikke indeholder hovedet kommune.

**Comment by Nobralyra** [comment]
Fixed: https://github.com/SDFIdk/gsearch/commit/160def377fbb395b76433169682490fc4b8a8c09
https://github.com/SDFIdk/gsearch/commit/ad2b4cecb79ee166364de33715ef1d1cd5d4c65a

**Comment by AnnetteSDFE** [comment]
testet ok
