### ISSUE TITLE
Geometri filter om bounding box 

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#157]
Jeg ved at **bounding box** ikke er en simple feature, men den vil være  praktisk for udvikleren at anvende som geografisk filter - med 2 sæt koordinater i stedet for 5. Men måske tager jeg fejl.

`geometri,SRID=25832;BBOX(515000.1 6074200.2, 555000.5 6104200.6)`
`geometri,SRID=25832;POLYGON((515000.1 6074200.2, 515000.3 6104200.4, 555000.5 6104200.6, 555000.7 6074200.8, 515000.1 6074200.2))) `

**Comment by AnnetteSDFE** [comment]
signe undersøger om det er muligt nu - samt tjekker dokumentationen

**Comment by Nobralyra** [comment]
Man kan godt søge ved hjælp af en bbox, men det skal stå som følgende: `filter=BBOX(geometri, 515000.1,6074200.2, 555000.5,6104200.6)`
Som det er lige nu, kan man kun angive koordinater der er i EPSG:25832, da det er hardcoded.

**Comment by AnnetteSDFE** [comment]
@Nobralyra 
vil du tilføje det i dokumentationen?
