### ISSUE TITLE
Matrikel response og schema

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#161]
Bør returnere:
- kommunekode // så man kan filtrere på kommune
- jordstykkeId // så man kan arbejde videre med resultatet
- SFE-nummer // (SFE = BFE-nummer)

**Comment by JesperKock** [comment]
#193 omhandler BFE numre

**Comment by claus-megaard-GST** [comment]
Hej @elvios @Glorforidor 
Vi ser i GST frem til at få jordstykkeid med i resultatet - er der nogen tidshorisont for det?
- i samme forbindelse vil det også være nyttigt at kunne søge med jordstykkeid som input

**Comment by klauskjaer** [comment]
Vi kan fra Septimas side kun bifalde, at servicen kommer til at understøtte JordstykkeID - det er et must for, at vi kan implementere den i de løsninger vi arbejder med.
