### ISSUE TITLE
Kommune visningstekst for Christiansø

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#164]
`Christiansø` har visningstekst `Christiansø Kommune` - bør bare være `Christiansø`

**Comment by AnnetteSDFE** [comment]
Fejlen er, at der tilføjes "kommune" efter Christiansø, når der søges i ressourcen kommune, da Christiansø ikke er en kommune.
Signe oplyser, at det er relativt nemt at tilføje en udtagelse i koden, så visningsteksten blot bliver "Christiansø"

**Comment by AnnetteSDFE** [comment]
mangler tjek i demo, når url er flyttet af johan

**Comment by AnnetteSDFE** [comment]
ok
