### ISSUE TITLE
Alfabetisk eller logisk rækkefølge af attributer i response/schema

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#169]

**Comment by AnnetteSDFE** [comment]
rækkefølge er valgt og fremgår af dokumentationen

**Comment by Nobralyra** [comment]
Rækkefølgen af attributer response/schema ændrer sig hver gang gsearch REST API bliver deployet. I følge JSON standarden https://www.rfc-editor.org/rfc/rfc8259#section-1, er det helt valid.
