### ISSUE TITLE
Multiple spaces right after each other results in https response code 400

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#170]
Fx.
Wakeup Copenhagen  Bernstorffsgade 
Wakeup Copenhagen - Bernstorffsgade

**Comment by Nobralyra** [comment]
Er ikke fikset med ` - `

**Comment by AnnetteSDFE** [comment]
er fikset, så man kan søge med to mellemrum og bindestreg. men fejler fortsat med to mellemrum og , . '
