### ISSUE TITLE
Resultater prioriteres på baggrund af det viste kortudsnit

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#171]
Hvis der er blevet filtreret med en geometri, skal response være sorteret efter geomtrien.

Kommer fra dette issue: https://github.com/SDFIdk/gsearch/issues/5

**Comment by AnnetteSDFE** [comment]
tjekkes at der kun kommer resultater inden for den valgte polygon

**Comment by Nobralyra** [comment]
Hvis der bliver filtreret på en geometri, har de returneret resultater en forbindelse til geometrien, om det så er intersects eller hvad der er blevet defineret geometrien skulle gøre.
