### ISSUE TITLE
Matrikelsøgning - vanskelige at bruge i Gsearch end i GeoSearch

### ISSUE THREAD

**Issue by UffeLIFA** [SDFIdk/gsearch#174]
Jeg har desværre - såvel brugere som udviklere - der undrer sig over, at GSearch’s søgemetodik/følsomhed afviger fra GeoSearch – nu da SDFI meddeler:

Flyt fra Geosearch til Gsearch
GSearch har i princippet samme funktionalitet og virkemåde som SDFI's nuværende søgekomponent, GeoSearch, men med en række forbedringer.

Mht. fritekstsøgningen i GSearch så afviger denne desværre fra GeoSearch, som vist nedenfor (med eksempel): 

GeoSearch (gammel):

https://api.dataforsyningen.dk/Geosearch?token=d065b4f62ae460e2d8d5d8cdc17b1e8f&search=44%20Kolding%20Markjorder%204.%20Afd.&resources=Matrikelnumre&limit=2 

som bl.a. returnerer den ønskede matr.nr. 44 Kolding Markjorder 4. Afd., som vist nedenfor:  

GSearch (ny)

https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel?q=44%20Kolding%20Markjorder%204.%20Afd.&token=d065b4f62ae460e2d8d5d8cdc17b1e8f&srid=25832&limit=2 

som ikke returnerer den ønskede matr.nr. 44 Kolding Markjorder 4. Afd. – eller andre forekomster.

Der bør gøres noget for at der ikke skal skrives ejerlavsnavne PRÆCIST som de er anført i matriklen (mindre følsomhed overfor spaces, punktummer, kommaer, Gl./Gammel osv.)

**Comment by JesperKock** [comment]
Ejerlavsnavnet behøves ikke skrives præcist og vi tager højde for ekstra mellemrum og tegn i kaldet. F.eks. vil søgningen [44 Kolding, Markjorder](https://api.dataforsyningen.dk/gsearch_test/v1.0/matrikel?q=44%20Kolding,%20Markjorder&limit=2) returnere følgende visningstekst:

```
"44, Kolding Markjorder 3.Afd."
"44, Kolding Markjorder 4.Afd."
```

Her er `4.Afd.` dog et ord i vores data (modsat kaldet) og derfor når du adskiller det med mellemrum vil det ikke give nogle resultater.

Det er dog noget vi er opmærksom på da det har forbindelse til dette issue:
https://github.com/SDFIdk/gsearch/issues/146
