### ISSUE TITLE
Søgning på udgåede matrikelnumre ønskes

### ISSUE THREAD

**Issue by GustafGST** [SDFIdk/gsearch#175]
Jeg kunne godt tænke mig hvis det var muligt at søge på udgåede matrikelnumre i GSearch

Det er noget jeg anvender i websiden https://mao.gst.dk til at søge på jordstykker tilbage i tiden.

Det anvendes f.eks. for at undersøge historiske sammenlægninger eller udstykninger. Typisk anvendes det af en landinspektør.

Søgningen har tidligere været mulig i Geosearch ved søgetypen matrikelnumre_udgaaet

![1](https://user-images.githubusercontent.com/125450051/219338853-cda4d421-9424-4c1e-a67e-ec0cb5a022be.png)

Hvis jordstykkets VirkningTil dato er ældre end nu er jordstykket historisk, modellen er på http://grunddatamodel.datafordeler.dk/
![2](https://user-images.githubusercontent.com/125450051/219339118-3cc52aa1-0b10-4e05-bb09-f5182e1827c2.PNG)

**Comment by AnnetteSDFE** [comment]
@GustafGST godt at høre, at du har fundet en løsning. Du må gerne lukke issue.
