### ISSUE TITLE
Filterering på kommunenummer

### ISSUE THREAD

**Issue by AsgerPetersen** [SDFIdk/gsearch#179]
QGIS-pluginet "GeoSearchDk" er relativt udbredt i den offentlige forvaltning. Der er feks mange kommuner og forsyninger, som benytter sig af pluginet i deres daglige arbejde.

For disse brugere er der i det eksisterende plugin lavet en konfigurerbar filtrering, så der kun søges resultater fra en eller flere kommuner: 
![image](https://user-images.githubusercontent.com/1392735/222710108-caecfd5b-d403-4118-a841-ad87783ec039.png)

Så vidt jeg kan læse af dokumentationen er dette ikke længere muligt med `gsearch`, da der kun er muligt at filtrere på kommunekode for **visse** af ressourcerne.

Det er feks ikke muligt at filtrere `matrikel` og `navngivenvej` efter kommunekode. Dette forhold gør det vanskeligt at beholde den eksisterende funktionalitet i pluginet, da det vil være yderst ulogisk, hvis resultatlisten består af en blanding af filtrerede og ikke-filtrerede poster.

Tag en kommunal medarbejder i Rudersdal kommune, som skal finde matrikelnummer `3kg`. I den nuværende plugin (som er konfigureret til at filtrere på kommunekode 230) indtaster medarbejderen `3kg` og får følgende resultat:

![image](https://user-images.githubusercontent.com/1392735/222711640-b5b1309f-cbaf-4b3b-972e-26981d049b73.png)

I gsearch vil medarbejderen få dette resultat:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/1392735/222712017-657b962f-1028-4b9c-9d56-a9811eb476ba.png">

Eller en medarbejder i Ringsted, som søger Søndergade:
![image](https://user-images.githubusercontent.com/1392735/222713860-2512af6a-fe24-4321-8ff4-e9752ce722c2.png)

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1392735/222714284-ac607bc6-3990-4521-a4bb-afef89d242d6.png">

Resultatet er, at den kommunale medarbejder fremover vil have markant sværere ved at finde frem til de steder, som vedkommende skal bruge.

**Comment by JesperKock** [comment]
Fixed in v1.1.0
