### ISSUE TITLE
Endpoint til søgning i alle ressourcer

### ISSUE THREAD

**Issue by AsgerPetersen** [SDFIdk/gsearch#180]
Hvis `gsearch` skal kunne fungere mere eller mindre som en drop-in replacement for geosearch, så mangler der et endpoint, der kan søge i alle ressourer på én gang.

Dette endpoint eksisterede i øvrigt, da det blev annonceret, at gsearch var gået i produktion. Det kunne kaldes på følgende form:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/search?resources=postnummer,adresse,husnummer&token=XXX&q=jer&limit=10

For QGIS pluginet [GeosearchDK](https://github.com/Septima/qgis-geosearch) betyder fraværet af dette endpoint, at der er brug for markant mere komplicerede ændringer.

Hvis `gsearch` skal have samme virkemåde og funktionalitet set fra QGIS GeosearchDKs perspektiv, så mangler dette endpoint, som tillader at søge på tværs af ressourcer med ét kald og som sammenstiller et resultat på max `limit` records. GeoSearch har logik, som ud fra antallet af hits fra hver ressource afgør, hvor mange records, der kan medtages fra hver enkelt ressource, så resultatet maximalt består af `limit` records.

Det er oplagt at det skal være muligt at skelne typen på de returnerede objekter fra dette endpoint. Altså feks en `type` property.

Desuden skal endpointet gerne kunne filtrere alle underliggende ressourcer på kommunekode (se #179 ).

**Comment by DocDemar** [comment]
Det vil ikke med Gsearch blive muligt med et request at søge i samtlige datakilder.
Vi har med Gsearch ønsket at opdele ressourcerne for på den måde at skabe mulighed for at differentiere konfigurationen af søgekriterier, sortering og filtreringer på baggrund af  features og attributter i de enkelte datakilder.
