### ISSUE TITLE
matrikelsøgning fejler/langsom

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#183]
Efter 10 sekunder returneres fejl på:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel?token=fd44f26ab5701c01ca9f570e507fe9ab&q=1&limit=10

søges på en lidt længere streng svares der efter 3+ sekunder:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel?token=fd44f26ab5701c01ca9f570e507fe9ab&q=1a&limit=10

**Comment by JesperKock** [comment]
Duplicate of https://github.com/SDFIdk/gsearch/issues/176

**Comment by klavspc** [comment]
> Duplicate of #176

Jeg er ikke helt enig i at dette er en dublet. Der er mange aspekter i #176.

Dette issue går på performance. Jeg er klar over, at der ikke gives nogle svartidsgarantier i beskrivelsen af servicen, men det er svært at lave en løsning ovenpå gsearch, hvis det skal tage 10+ sekunder at få ti jordstykker, der starter med "1" (eller 3+ sekunder for "1a")

**Comment by klavspc** [comment]
> Det ville hjælpe os du kunne fortælle os hvad i forventer at finde ved at søge efter `1` eller `1a`? Resultaterne ville være fra hele landet.

Vi ville forvente at finde matrikelnumre, der starter med "1" eller "1a" i modsætning til f.eks. "2"

Vore løsninger går ud på at lade brugeren hurtigst muligt kunne vælge et matrikelnummer. Så jo hurtigere det dukker op jo bedre. Kombineret med #186 kan der opnås en rigtig god brugeroplevelse

**Comment by JesperKock** [comment]
Fixed in v1.1.0
