### ISSUE TITLE
stednavnesøgning fejler

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#184]
Denne url:

https://api.dataforsyningen.dk/rest/gsearch/v1.0/stednavn?token=fd44f26ab5701c01ca9f570e507fe9ab&q=e&limit=10

fejler med
```
{
 status: "BAD_REQUEST",
 message: "Input invalid",
 errors: null
}
```

**Comment by DocDemar** [comment]
Hej Klavs

vi kigger på det - 
Medens vi gør det kunne du så hjælpe os ved at skifte til en token der tilhører din egen Dataforsyningen bruger
Du kan oprette en bruger på https://dataforsyningen.dk hvis ikke du allerede har en bruger
