### ISSUE TITLE
Stort ønske om at kunne angive kommunekode som filter for dagi, mat og stednavne

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#186]
Dette er et stort ønske

Langt de fleste af vore kunder foretager søgninger, hvor kun resultater fra deres kommune ønskes - stort set alle søgninger mod den udgående GeoSearch var med kommunekode som filter

Specielt søgninger i MAT vil give vore kunder besvær, idet mange mat# er gengangere nationalt

NB:
Se også #183 : Søgning kvalificeret med kommunekode vil alt andet lige performe bedre end uden kommunefilter

**Comment by JesperKock** [comment]
Pt. kan du søge efter `ejerlavskode` i `maktrikel`.

Jeg bringer ønsket om kommunekode i `matrikel` videre.

**Comment by Ellebjerg** [comment]
Filter på kommunekode i matrikelsøgning er helt uundværligt i den kommunale hverdag.

**Comment by DocDemar** [comment]
> Filter på kommunekode i matrikelsøgning er helt uundværligt i den kommunale hverdag.
Hej Lars
opgaven er i backlog til den kommende 1.1.0 release

**Comment by JesperKock** [comment]
Duplicate of #179
