### ISSUE TITLE
Der bør ikke ses bort fra foranstillede cifre i søgestreng mod kommune og postnummer

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#187]
Der ses tydeligvis bort fra foranstillede cifre i disse søgninger
https://api.dataforsyningen.dk/rest/gsearch/v1.0/kommune?token=fd44f26ab5701c01ca9f570e507fe9ab&q=12a&limit=10
https://api.dataforsyningen.dk/rest/gsearch/v1.0/postnummer?token=fd44f26ab5701c01ca9f570e507fe9ab&q=12a&limit=10
![image](https://user-images.githubusercontent.com/3736091/228831270-6d1c1404-e0cb-493d-bb98-e6b0767b824e.png)

Vi vil opfordre til at dette ændres. Hvis brugeren skriver "12a" så bør der søges med det.

I vore løsninger, som kombinerer resultater fra flere kilder, kan det komme til at se ud som nedenfor. Dette er ikke den oplevelse vore brugere forventer
![image](https://user-images.githubusercontent.com/3736091/228831842-8e4d7745-cd6d-4aae-86cf-5e23af504e38.png)
Og hvis brugeren klikker videre til "Kommuner" ses:
![image](https://user-images.githubusercontent.com/3736091/228832291-bdb9167d-3dd9-43b0-9cf5-9a8d05796ccd.png)

**Comment by JesperKock** [comment]
Fixed in v1.1.0
