### ISSUE TITLE
Falske resultater, idet der matches mod redundante data i visningstekst

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#188]
Ved søgninger mod kommune søges der også i den faste streng "kommune". Det tilfører ikke værdi til søgningen, idet match mod "kommune"  ikke begrænser resultatet

Dette match bør undlades - søg istedet i _kommunenavn_ og _kommunekode_.

Eksempel:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/kommune?token=fd44f26ab5701c01ca9f570e507fe9ab&q=kom&limit=10

![image](https://user-images.githubusercontent.com/3736091/228833892-cbf10858-eb72-4ee8-b7e2-3cba28118812.png)

Overvej også gerne samme forhold for _region_

**Comment by Nobralyra** [comment]
Kommune endpoint: Use 'kommunenavn' instead of 'visningstekst' in textsearchable
https://github.com/SDFIdk/gsearch/commit/ca7de7a1940206f02ac889f62bae4cc90f1d4285

Fixed in release v1.1.0.
