### ISSUE TITLE
Overvej behandlingen af foranstillede nuller (0) i kommune-søgning

### ISSUE THREAD

**Issue by klavspc** [SDFIdk/gsearch#189]
Ved søgning på "101" mod _kommune_ findes ingen resultater. Det vil give vore slutbrugere en bedre oplevelse ikke at skulle huske foranstillet "0" (unødvendigt og redundant)

https://api.dataforsyningen.dk/rest/gsearch/v1.0/kommune?token=fd44f26ab5701c01ca9f570e507fe9ab&q=101&limit=10
![image](https://user-images.githubusercontent.com/3736091/228836199-664332e6-4694-4d3c-8333-6273052d1674.png)

![image](https://user-images.githubusercontent.com/3736091/228836741-8b6f4ca5-ad05-4303-8f3c-a3e7b2354a7a.png)

**Comment by Nobralyra** [comment]
Muliggør type ahead søgning på kommunekode and search without prefix zero:
https://github.com/SDFIdk/gsearch/pull/194

Fixed in release v1.1.0.
