### ISSUE TITLE
Returner numre som number

### ISSUE THREAD

**Issue by haakseth** [SDFIdk/gsearch#190]
Så vidt jeg kan se, returneres alle numre som string, undtagen de der er inde i en geometri-type. Det giver god mening i tilfælder som postnumre, kommunenumre etc, men burde det ikke som hovedregel returneres som `number`?

Exempel, [matrikelkald](https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel?token=fd44f26ab5701c01ca9f570e507fe9ab&q=162&limit=1) - ejerlavskode, centroid_x, matrikelnummer og centroid_y kunne måske med fordel været number?

**Comment by DocDemar** [comment]
Har du mulighed for at uddybe hvilke praktiske konsekvenser har det at tal returneres som strings?

**Comment by haakseth** [comment]
Som slutbruger af api-services er det godt at tal er returneret som faktisk `number`, da jeg ofte skal bruge det videre i kode som tal. 

I nogle tilfælder, som i centroide-exemplet over, skal tallet bruges videre i aritmetiske operationer eller lignende. Da giver det mig en tryghed at apiet returnerer number, så jeg selv slipper for at først gøre en parseFloat med evt fejlhåndtering.

I andre tilfælder, hvor det er snak om IDer af forskjællig art, er det ikke altid lige så kritisk. Nogle, som postnumre og kommunenumre, er jo de-facto standardiseret som strings, fordi de kan ha ledende 0-ere. Så må de gerne være strings.

Andre IDer, som f ex BFE-numre skal dog ofte bruges videre i [services](https://confluence.sdfi.dk/pages/viewpage.action?pageId=16056582#REST(BBR)-Metode-ejendomsrelation) der forventer at id er number. Da giver bedst mening at et api også returnerer det som number.

**Comment by AnnetteSDFE** [comment]
løsningen skal implementeres for alle ressourcerne.

**Comment by JesperKock** [comment]
Implemented in: https://github.com/SDFIdk/gsearch/releases/tag/v2.0.0
