### ISSUE TITLE
Søgning på gældende og historiske matrikelnumre og BFE-nummer

### ISSUE THREAD

**Issue by peter-gst** [SDFIdk/gsearch#191]
Geodatastyrelsen har et meget stort ønske om, at det i den nye Gsearch bliver muligt at søge på gældende og historiske matrikelnumre og BFE-numre. Geodatastyrelsen er i samarbejde med vores leverandør i gang med at udvikle en udstillingsplatform, der anvender Gsearch. I udstillingsplatformen bliver det muligt at se det nugældende og historiske matrikelkort + matrikelregister, og derfor vil det være højaktuelt at kunne fremsøge både gældende og historiske ejendomsidentifikationer såsom matrikelnumre og BFE-numre.

Geodatastyrelsen ved, at der er et stort anvenderbehov for dette, og har flere brancher, der har udtrykt stor efterspørgsel på netop dette emne. Der er i dag på Datafordeleren mulighed for at hente historiske matrikeldata tilbage til 2018, men Geodatastyrelsen arbejder foreløbigt på at indføre historik tilbage til 2002.

Funktionaliteten har tidligere været tilgængelig på den forhenværende Geosearch, og anvendelsesbehovet er i høj grad stadig tilstedeværende.

For den videre dialog om behov og implementeringsønsker bedes der rettes henvendelse til Claus Megård: clasm@gst.dk

**Comment by JesperKock** [comment]
Med historiske matrikler mene GST så at  i geosearch var der både `matrikelnumre_incl_udgaaet` og `matrikelnumre_udgaaet`?

I forbindelse med #175 havde vi snakket om hvordan vi ville implentere udgået matrikler og det ville nok komme som et nyt endpoint.

**Comment by elvios** [comment]
Har oprettet et separat issue til det med BFE-numre: #193

**Comment by elvios** [comment]
@peter-gst Vi har mulighed for at lave et endpoint, der hedder fx: `/matrikel_udgaaet`. Men som du siger, er der - lige nu - kun historik tilbage til 2018.

**Comment by peter-gst** [comment]
Det lyder fint at det er et særskilt endpoint. Historik tilbage til 2018 er GST med på.

- Kan SDFI komme med et estimat på tidshorisont på denne opgave?

**Comment by JesperKock** [comment]
Vi har ikke lavet en git release endnu, men det burde være i produktion nu.

**Comment by claus-megaard-GST** [comment]
@JesperKock - det ser ud til at `/matrikel_udgaaet` er kørende
Den returner dog der uventet mange hits

F.eks. giver https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel_udgaaet?q=1bb&filter=ejerlavskode=%27620951%27&token=92867c504e19e219777518cd205778e8
8 hits

Her havde jeg kun forventet 1 resultat (den hvor status="historisk")

<img width="537" alt="image" src="https://github.com/SDFIdk/gsearch/assets/117916270/c2c7aa23-75a0-4d92-b1b6-8aa39e36130c">

**Comment by elvios** [comment]
Aha. Jeg tror ikke, at vi var helt klar over hvad "historisk" betoed.

@claus-megaard-GST hvis vi nu kun viser alle de matrikler med `status = 'Historisk'` og `registreringtil IS NULL`, vil det saa returnere det I gerne vil have?

**Comment by claus-megaard-GST** [comment]
@elvios 
i stedet for at slette matrikelnumre/bfe-numre bliver de gjort historiske

Ja det burde virke med `status = 'Historisk'` og `registreringtil IS NULL`, 
Men for en sikkerheds skyld må I også hellere tilføje `virkningtil IS NULL` 
(hvis vi på et tidspunkt skulle finde på at lave en fejlrettelse af en historisk ejendom)

**Comment by elvios** [comment]
@claus-megaard-GST , det er nu deployet til produktion. Baade med `status`, `registreringtil` og `virkningtil`.

Den URL du sendte tidligere returnerer nu kun 1 matrikel. (https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel_udgaaet?q=1bb&filter=ejerlavskode%3D%27620951%27&token=92867c504e19e219777518cd205778e8)

Der er dog ikke nogle ejerlav eller kommuner, som har `status=Historisk`. Saa kommunekode, kommunenavn, ejerlavskode og ejerlavsnavn er fra de gaeldende kommuner og ejerlav. Kan dette vaere misvisende, tror du?

**Comment by AnnetteSDFE** [comment]
@claus-megaard-GST Har du mulighed for at se på denne ? mvh Annette

**Comment by claus-megaard-GST** [comment]
@elvios 
Administrative områder (Ejerlav, Sogn og kommune) får kun `status=Historisk` hvis området helt nedlægges (f.eks. ved sammenlægning)
- det sker sjældent for ejerlav og kommuner , men der sker lidt med sognene
- det sker også sjældent at disse områder skifter navn, så risikoen for at det kan være misvisende er minimal.

**Comment by AnnetteSDFE** [comment]
@claus-megaard-GST tak for svar - vil det sige, at I godt kan acceptere den nuværende implementering, så sagen kan lukkes? mvh Annette

**Comment by claus-megaard-GST** [comment]
Ja, for min skyld må I gerne lukke den
