### ISSUE TITLE
Ved stednavneobjekter, som falder i flere postdistrikter, vises beliggenheden (lokaliteten) ikke i parentesen - se den lukkede sag #32

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#201]
Det er teksten i parentes, der mangler stedbetegnelse (beliggenhed)

Filsø Ellipsen har kun (vej/sti).

Forskellige bebyggelser får ikke vist beliggenhed, sandsynligvis fordi de strejfer postnummergrænsen fra DAGI. Er det muligt at ændre visning til det område, som objektet overvejende ligger indenfor?

**Comment by Nobralyra** [comment]
Jeg lavede nogle ændringer i sidste uge til stednavnes hjælpetekst, for at flere havde topografien og lokationen i den.
Det gør blandt andet at `Filsø Ellipsen (vej/sti)` har ændret sig til `Filsø Ellipsen (Sti i Henne)`.
![image](https://github.com/SDFIdk/gsearch/assets/48592380/e53adbc4-4d7d-4950-8f51-13d2f1924f78)


Nogle af udfordringenerne er, som du selv skriver, at der er en masse stednavne som strejfer postnummergeometrierne fra DAGI, andre stednavne som slet ikke ligger i nærheden af nogle postnummergeometrierne, og andre som ligger 50% i to forskellige postnummergeometrier.
