### ISSUE TITLE
Status code 504 (Gateway Timeout) on husnummer resource

### ISSUE THREAD

**Issue by sweco-dkgemr** [SDFIdk/gsearch#203]
We tried making the below call to the API using the husnummer resource:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/husnummer?q=1&limit=15&token=XXXXXXXXXXX
It results in a status code 504 (Gateway Timeout)

This is probably due to the fact that there is a hugh amount of houses in Denmark with the house number 1
I presume that the way the API works is that it finds all the results before returning only the limited number back and therefore it takes quite some time to generate the result.
Instead you could consider that you only generates search result until there is enough to satisfy the limited amount.
![Error screenshot](https://github.com/SDFIdk/gsearch-ui/assets/62336024/b64f9df3-222b-42d1-b40f-f20f0b7e2064)

**Comment by iamfrank** [comment]
Thanks for reporting @sweco-dkgemr . We moved the issue to the repo with where the right people can take a look at it.

**Comment by JesperKock** [comment]
We are aware that `adresse` and `husnummer` is slow with single digit `q` parameters.

We do check if the search parameter has more than 1000 hits and use a simplified search to return a response faster. But this optimization is not implemented on `adresse.husnummer` and `husnummer.husnummertekst`.

I tried adding `adresse.husnummer` and `husnummer.husnummertekst` and single digit `q` parameters now responds in about 50ms. But this also slows down a few other searches. So we won't be pushing out an update before more testing.

**Comment by Nobralyra** [comment]
Just for your information, right now we are working on another project, so this is on hold for some time, but hopefully we can look further on this soon again.
