### ISSUE TITLE
Manglende resultater ved kommunefiltrering

### ISSUE THREAD

**Issue by sweco-dkjesh** [SDFIdk/gsearch#205]
I nogle tilfælde mangler der søge resultater, når man søger med kommunekode filter.

Fx
Gyrstinge Sø ligger delvist i Holbæk og delvist i Ringsted.
Hvis man søger i stednavne uden kommune filtering kan Gyrstinge Sø fremsøges. Men hvis man søger med kommunekode bliver den ikke fundet.
Det er forventet at den søen bliver fundet i begge kommuner, som den gjorde i GeoSearch.

https://api.dataforsyningen.dk/rest/gsearch/v1.0/stednavn?q=gyrstinge%20s&limit=15&token=7030997b12f9e91e9da29f0c6e24a845&filter=kommunekode=%270329%27
Returnerer:
[]

https://api.dataforsyningen.dk/rest/gsearch/v1.0/stednavn?q=gyrstinge%20s%C3%B8&limit=15&token=7030997b12f9e91e9da29f0c6e24a845
Returnerer:
[
    {
        "skrivemaade_uofficiel": "",
        "skrivemaade_officiel": "Gyrstinge Sø",
        "bbox": {
            "type": "Polygon",
            "coordinates": [
                [
                    [
                        668243.63,
                        6152913.2
                    ],
                    [
                        668243.63,
                        6155607.32
                    ],
                    [
                        671153.29,
                        6155607.32
                    ],
                    [
                        671153.29,
                        6152913.2
                    ],
                    [
                        668243.63,
                        6152913.2
                    ]
                ]
            ]
        },
        "skrivemaade": "Gyrstinge Sø",
        "stednavn_subtype": "sø",
        "stednavn_type": "soe",
        "geometri": {
            "type": "MultiPolygon",
            "coordinates": [
                [
                    [
                        [
                            668282.71,
                            6155051.11
                        ],
                        ...
                       [
                            668282.71,
                            6155051.11
                        ]
                    ]
                ]
            ]
        },
        "id": "1233766a-2d18-6b98-e053-d480220a5a3f",
        "visningstekst": "Gyrstinge Sø (Sø i Ringsted)",
        "kommunekode": "0316,0329"
    }
]

**Comment by JesperKock** [comment]
Du skal bruge `like` i stedet for `=` når du bruger kommunekode. Se evt. eksemple i dokumentationen: https://docs.dataforsyningen.dk/#filter

Så kaldet vil virke hvis det ser sådan her ud:
`https://api.dataforsyningen.dk/rest/gsearch/v1.0/stednavn?limit=15&q=gyrstinge%20s&filter=kommunekode%20like%20%27%250329%25%27&token={TOKEN}`

Husk at dine tokens er personlige.

**Comment by sweco-dkjesh** [comment]
@JesperKock Tak for hjælpen :-). Vi havde ikke set eksemplet. Og tak fordi du fjernede vores token fra issuet.
