### ISSUE TITLE
Udgået jordstykke kan ikke fremsøges

### ISSUE THREAD

**Issue by klauskjaer** [SDFIdk/gsearch#207]
Matr.nr. 8k, Heden By, Heden (441051) kan ikke fremsøges som et udgået jordstykke, idet dette kald returnerer et tomt svar:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel_udgaaet?q=8k,441051&limit=100&token=92867c504e19e219777518cd205778e8
JordstykkeID 1788584
Jordstykket er udgået 26-08-2021.
Den ejendom, som jordstykket indgik i (BFEnr 7998600), er stadig gældende - måske er det det, der driller?

Vi har ingen problemer med at fremsøge andre udgåede jordstykker , fx dette:
https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel_udgaaet?q=1bb,620951&limit=100&token=92867c504e19e219777518cd205778e8

Septima ref: https://github.com/Septima/gstmat-udstillingsprojekt/issues/219

**Comment by JesperKock** [comment]
Det ser ud til at da vi satte `bfenummer` på `matrikel_udgaaet` fik fjernet de resultater der ikke havde et `bfenummer`, de er nu inkluderet igen med `bfenummer` sat til `NULL`.

Dit link giver et resultat nu.
