### ISSUE TITLE
Adresser med supplerende bynavne fejler

### ISSUE THREAD

**Issue by seskildsen** [SDFIdk/gsearch#208]
Hvis man søger efter en adresse der har et supplerende bynavn i sig, fejler søgningen, fx. `Småkærvej 48, Hejsager, 6100 Haderslev`, hvis man fjerner `Hejsager`, kan man godt fremsøge adressen `Småkærvej 48, 6100 Haderslev`.

`https://api.dataforsyningen.dk/rest/gsearch/v1.0/adresse?q=Fredesh%C3%B8j%208,%20Hejsager,%206100%20Haderslev`

`https://api.dataforsyningen.dk/rest/gsearch/v1.0/adresse?q=Sm%C3%A5k%C3%A6rvej%2048,%206100%20Haderslev`

Det samme er tilfælde for navngivenvej og husnummer

**Comment by JesperKock** [comment]
Implemented in: https://github.com/SDFIdk/gsearch/releases/tag/v2.0.0
