### ISSUE TITLE
Partial matching af Postnumre

### ISSUE THREAD

**Issue by shtirlitsDva** [SDFIdk/gsearch#209]
Når jeg søger efter f.eks. Algade 43 (i register Adresser), så ud over alle de virkelige Algader 43, får jeg også en hel masse Algader, hvor der kun er en del af postnummeret der matcher f.eks. Ahlgade 1C, 4300 Holbæk. Dvs. jeg får også alle adresser fra Ahlgade i Holbæk, fordi deres POSTNUMMER starter med 43. Det betyder også, at jeg rammer loftet for 100 resultater i den forespørgsel.

Jeg mener det må være en uhensigtsmæssig funktionalitet, at der matches med delvise postnumre. For mig lyder det meget ulogisk at søge efter et vejnavn og delvist i postnummeret, for hvad ville så formålet være med den søgning? Men der kan være andre use cases, selvfølgelig, som jeg ikke kender til.

Så jeg vil gerne foreslå en forbedring, hvor POSTNUMMER matches fuldstændigt eller slet ikke.

Det gamle geosearch fungerede ikke sådan i hvert fald.

**Comment by JesperKock** [comment]
Da Gsearch er lavet som en typeahead søgning er det nok ikke noget vi lige ændre tilbage.

Hvis du ønsker at reducere antallet af resultater vil jeg anbefale du bruger filtre.
F.eks: https://api.dataforsyningen.dk/rest/gsearch/v1.0/adresse?q=Algade%2043&filter=postnummernavn%3D'Sk%C3%A6rb%C3%A6k'

Jeg lukker issuet.
