### ISSUE TITLE
 `navngivenvej` - tilføj `postnummer` + `postnummernavn` til `visningstekst`

### ISSUE THREAD

**Issue by DKbest** [SDFIdk/gsearch#214]
I `navngivenvej` er der samme outputværdi for henholdsvis `vejnavn` og `visningstekst`

**Forslag** at der tilføjes `postnummer` + `postnummernavn` til `visningstekst`, på samme måde som det gøres for `adresse`

![image](https://github.com/SDFIdk/gsearch/assets/79503214/9beca260-a1d3-4d9a-a8c5-dc834162f367)

**Comment by seskildsen** [comment]
Der er allerede oprettet et issue (https://github.com/SDFIdk/gsearch/issues/132) der beskriver det samme, så lukker dette.
