### ISSUE TITLE
DAGI geometrier fra DAWA

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch#227]
En anvender fra NetCompany har gjort opmærksom på at G-search trækker DAGI geometrier fra DAWA. (link til henvendelse følger)
det skal generelt undersøges om der trækkes på DAWA for andre ressourcer.

**Comment by seskildsen** [comment]
Gsearch trækker ikke direktre fra DAWA, men DAWA og gsearch trækker fra samme sted som er vores interne DAGI database (i Databanken).
Gsearch trækker ingen datasæt fra DAWA.
