### ISSUE TITLE
Den indtastede søgestreng skal komme først i resultatet

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#28]
”Lind” skal komme øverst, når man søger på netop den streng, det gør det ikke i Geosearch nu
(Lind er bydel i Herning)

**Comment by DocDemar** [comment]
@cfischer00  Er dette issue fikset?

**Comment by cfischer00** [comment]
Jeg tror det. Jeg tjekker når jeg skriver dokumentationen

**Comment by AnnetteSDFE** [comment]
Vil I tjekke om denne er løst?

**Comment by cfischer00** [comment]
Det er løst

**Comment by AnnetteSDFE** [comment]
Anette K skal teste vha Johans implemtering på dataforsyningen

**Comment by AnnetteSDFE** [comment]
testet dd - ikke løst

**Comment by AnetteKlinker** [comment]
Andre eksempler kan være "Møn" eller "Års"

**Comment by AnnetteSDFE** [comment]
er umiddelbart svær at løse.

**Comment by Nobralyra** [comment]
`Egholm` er endnu et eksempel

**Comment by Nobralyra** [comment]
Tror måske en løsning kan være at bruge levenshtein, som set her:
https://github.com/SDFIdk/DAWA/blob/2ceec22548303ae21b24b7ddf3ed4ce2a9a0a2cc/packages/server/apiSpecification/common/sql/sqlParameterImpl.js#L288
https://github.com/SDFIdk/DAWA/blob/2ceec22548303ae21b24b7ddf3ed4ce2a9a0a2cc/packages/server/apiSpecification/adresse/sqlModel.js#L121

**Comment by AnnetteSDFE** [comment]
løst i vers 1.1.0
