### ISSUE TITLE
Stednavne i flere ord skal kunne fremsøges med blanktegn mellem delene

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#29]
”Fanø Vesterhavsbad” skal kunne søges sådan, pt kommer det allersidst af søgeresultaterne, og ikke som nu sammenskrevet til ”Fanøvesterhavsbad” for at det skal komme først.

**Comment by cfischer00** [comment]
Fungerer:
SELECT * FROM api.stednavn ('Fanø Vesterhavsbad', NULL, NULL, 100)
