### ISSUE TITLE
Det skal være muligt at søge navne hvori specialtegn som "/" indgår

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#30]
Navnet ”H/F Prøvestenen” skal kunne fremsøges (”/” kan ikke anvendes i søgestreng p.t.). Man kan dog søge med tegnerstatning: h&sol;f eller h?f eller h*f

**Comment by cfischer00** [comment]
Kan fremsøges i GSearch:

SELECT * FROM api.stednavn ('H/F p', NULL, NULL, 100)
