### ISSUE TITLE
Ved stednavneobjekter, som falder i flere postdistrikter, vises beliggenheden ikke 

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#32]
Eksempler: Charlottenborg, Wakeup Copenhagen - Bernstorffsgade, Filsø Ellipsen

**Comment by Nobralyra** [comment]
Dette er et frontend problem på hvad jeg gætter er sdfikort.dk. På gsearch-ui og i gsearch response kommer der en geometri med.

**Comment by AnnetteSDFE** [comment]
snak med anette k

**Comment by AnetteKlinker** [comment]
Filsø Ellipsen får ikke vist beliggenhed.

Forskellige bebyggelser får ikke vist beliggenhed, sandsynligvis fordi de strejfer postnummergrænsen fra DAGI. Er det muligt at ændre visning til det område, som objektet overvejende ligger indenfor?
