### ISSUE TITLE
Kan ny Geosearch erstatte DAWA.AWS?

### ISSUE THREAD

**Issue by AnetteKlinker** [SDFIdk/gsearch#44]
På møde mellem Jørgen, Elvis, Katarina, Morten og Anette d. 12. oktober blev det nævnt at stednavne ikke skal være en del af API.DAWA længere. Og at Geosearch måske kan komme til at erstatte DAWA.AWS for stednavnes vedkommende.

**Comment by cfischer00** [comment]
GSearch kan udstille stednavne-søgning
