### ISSUE TITLE
Textsearchable_column restruktureres

### ISSUE THREAD

**Issue by Aramos93** [SDFIdk/gsearch#49]
Textsearchable_column, der omdanner søgningstekst til full_text_search lexemes, skal defineres for de enkelte searchers.
Søgestrengen opdeles i enkelte ord og hver del vægtes afhængig af dets betydning for søgerangering. Vægtene er A, B, C, D (hvor A har højest vægt og D har lavest)

Umiddelbart bud:
- [ ] **Postnr**: postnummer: A, Første ord af navn: B, næste ord af navn: C, resten af ord i navn: D
- [ ] **Sogne**: Sognekode:  A, Første ord af navn: B, næste ord af navn: C, resten af ord i navn: D
- [ ] ... (resten tilføjes)

**Comment by cfischer00** [comment]
Er implementeret
