### ISSUE TITLE
Full-text-search configuration

### ISSUE THREAD

**Issue by Aramos93** [SDFIdk/gsearch#50]
Der bør bruges en blanding af `danish` og `simple` dictionary i full-text-search configurationen, eftersom stopnavne som `ved`, `i` `den/det` ect. kan indgå i vejnavne/stednavne og ikke skal ignoreres. Til gengæld vil vi gerne specificere en thesaurus med danske regler som f.eks. `aa -> å`,  `skt. -> sankt` `Ndr.-> Nordre`, `st. -> store`

**Comment by cfischer00** [comment]
Jeg mener den er implementeret
