### ISSUE TITLE
Matrikel response og schema

### ISSUE THREAD

**Issue by Aramos93** [SDFIdk/gsearch#56]
Morten Lind fortalte at der om vejmatrikler alene bruges slutbogstavet i hverdagstale. Så i stedet for `7000a` bare referes til `a`. Er dette en søgning vi vil understøtte eller bør man konsekvent bruge det fulde navn således at alle matrikelnumre starter med et tal? @cfischer00

**Comment by AnetteKlinker** [comment]
Jeg synes det giver mening, at der søges på '7000x', men har det stor betydning i kodningen, når stednavne skal kunne søges som enkeltbogstaver, om matrikelnumre så også kan?

**Comment by Aramos93** [comment]
Ja det har en betydning, da vejmatrikler sådan set ikke hedder blot `a` eller `b` i eksisterende data men `7000a` og `7000b`, så der skal laves nogle aliaser for dem, hvis det skal understøttes.

**Comment by Nobralyra** [comment]
Matrikel svarer strikt på q-parametren - for q=12 returneres kun jordstykker med matrikelnummer '12' - ikke 12a, 12b eller 122 eller ... - er det bevidst? Mit synspunkt: så længe q starter med et ciffer og derefter evt. har et bogstav, skal response foreslå mulige matrikelnumre med flere tal/bogstaver. Hvis q der efter cifte+evt. bogstave er tilføjet et skilletegn (space/, o.l.) er det et tegn på at bbugeren "er færdig" med matrikelnummeret, hvorfor response skal foreslå de ejerlav, hvori dette matrikelnummer findes.

**Comment by JesperKock** [comment]
Pt. vil endpointet `matrikel` ikke blive ændret til at tallet i matrikelnummer kan undlades.
