### ISSUE TITLE
søgning på Sogne giver for mange resultater

### ISSUE THREAD

**Issue by AmandaWS** [SDFIdk/gsearch#58]
Hvis jeg søger på "agger" får jeg følgende resultater:

```
"Aggersborg sogn"
"Agger sogn"
"Agerbæk sogn"
"Agerskov sogn"
"Agersted sogn"
"Agersø sogn"
"Agerø sogn"
```

> https://gsearch.k8s-test-121.septima.dk/geosearch?search=agger&resources=sogn&limit=20

Jeg forventer kun at få de første to resultater.

-------------

Jeg får de samme søgeresultater men i anden sortering da jeg søger på "ager"

> https://gsearch.k8s-test-121.septima.dk/geosearch?search=ager&resources=sogn&limit=20

```
"Agerbæk sogn"
"Agerskov sogn"
"Agersted sogn"
"Agersø sogn"
"Agerø sogn"
"Aggersborg sogn"
"Agger sogn"
```

Her forventer jeg at få de 5 øverste resultater.

**Comment by AmandaWS** [comment]
Andre eksempel er søgning på "ball" som giver 5 resultater:

```
"Ballerup sogn"
"Balle sogn"
"Balling sogn"
"Ballum sogn"
"Balslev sogn"
```

Hvor den sidste er sneget sig med.

------------

Søgning på "ege" giver 14 resultater, hvor det sidste er `"Eggeslevmagle sogn"`. De øvrige 13 starter på _ege_.

**Comment by Aramos93** [comment]
Jeg vil vove at påstå at det er en feature og ikke en bug, at der kommer ekstra resultater med. Der tages højde for fonetik og diverse stavemåder, så man netop kan søge på forskellige stavemåder af samme navn f.eks. `christian/kristian` eller `skt/sankt/sct`, og `gammel/gamle/gl`. Specifikt for dette issue gælder det at dobbelt-konsonanter behandles som hvis det var en enkelt konsonant, men den søgte streng får altid højest prioritet.

Derfor  foreslår en søgning på `agger` netop ting der starter med `agger` øverst i resultatlisten, altså `Aggersborg - og Agger sogn`, og derefter ting der starter med `ager` (altså med ét enkelt `g`). Og på samme måde gælder det for `ager`, returneres først objekter der starter med `ager` derefter ting der starter med `agger` - `Agger og Aggersborg`. 

Det samme gælder for søgningen på `ball`.

At `århus/aarhus` returnerer både `Aarhus og Aarup sogn` er diskutabelt da det er et biprodukt af hvordan den fonetiske funktion fungerer. Den skal muligvis tweakes. Men som udgangspunkt er det fint at der returneres mere end mindre, så længe at det mest relevante er øverst, da resultaterne skal tolkes som mulige forslag til brugeren.

**Comment by cfischer00** [comment]
Work as designed. Not a bug - a feature
