### ISSUE TITLE
bruger dokumentation

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch#86]
dokumentation for hvordan man benytter Gsearch og implementerer funktionen i en web løsning

**Comment by AnnetteSDFE** [comment]
https://docs.dataforsyningen.dk/#geosearch

**Comment by JesperKock** [comment]
Gsearch API er tilføjet til den nye docs.dataforsyningen.dk.

**Comment by JesperKock** [comment]
http://load218.kmsext.dk:6400/#gsearch

**Comment by JesperKock** [comment]
Dokumentation skal opdateres i forholdt til multiple endpoints.

**Comment by AnnetteSDFE** [comment]
jeg har tilføjet nogle forslag til rettelser her:
Sag "1493-4028, Gsearch, ANPET, Emnesag" https://sdfeesdhp2022.sdfe.dk/app/client/#/Files/96052
