### ISSUE TITLE
NPM pakke 

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch#87]
Udstille en NPM pakke med kode til søgefelt mv og mulighed for konfiguration af Gsearch

**Comment by iamfrank** [comment]
@DocDemar Tænker du på https://www.npmjs.com/package/@dataforsyningen/gsearch-ui ?

**Comment by DocDemar** [comment]
Jeg tænkte på en lidt mere tilskåret og ready to go npm pakke som man kan inkludere på et website

**Comment by iamfrank** [comment]
> Jeg tænkte på en lidt mere tilskåret og ready to go npm pakke som man kan inkludere på et website

Jeg tror at https://www.npmjs.com/package/@dataforsyningen/gsearch-ui  opfylder de krav, men det kan være, det skal uddybes lidt.

**Comment by iamfrank** [comment]
Efter samtale IRL har vi fundet, at det behov dækkes fint af GSearchUI
https://github.com/SDFIdk/gsearch-ui
