### ISSUE TITLE
opdater datagrundlag

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch#91]

**Comment by AnnetteSDFE** [comment]
DAGI - er overført 
DAR - er overført
Stednavne - igang
Matrikel - afventer

**Comment by AnnetteSDFE** [comment]
DAGI - er overført
DAR - er overført
Stednavne - er overført
Matrikel - er overført

**Comment by AnnetteSDFE** [comment]
annette tager kontakt til Anette Klinker ift. stednavne når testurl er klar
