### ISSUE TITLE
opdateringsfrekvens

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch#92]
Opdateringsfrekvensen sker på ugentligt basis.

Når deltaopdateringer er muligt, så ændres opdateringsfrekvens til dagligt og dette issue lukkes.

Filen https://github.com/SDFIdk/gsearch/blob/main/doc/README.md skal opdateres med den relevante information.

**Comment by elvios** [comment]
Fra gsearch version 2.0 opdateres nogle af resurserne dagligt. 
Dette gaelder: `husnummer`, `adresse`, `navngivenvej`, `matrikel` og `matrikel_udgaaet`.

De resterende resurser opdateres stadig ugentligt.
