### ISSUE TITLE
Dobbelt ord i presentation strings

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch#95]
fjern dobbelt ord i prensentation string som for Kirkegård

**Comment by JesperKock** [comment]
Fundne redundant navngivning i stednavne (skrivemåde)
({type} i {by}) -> ({by})
- Begravelseplads
- Bro
- Kilde
- Sluse
- Rasteplads
- Bugt
- Sund
- Batteri
- Skanse

Andre rettelser
by i {kommune} -> By i {kommune}
(bebyggelse / Bebyggelse) -> (Bebyggelse)?
(vej / Bro) -> (Vej / Bro) : Ret alle dem der er opdelt med slash og starter med småt
