### ISSUE TITLE
FIlter query parameter fails

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/gsearch#98]
Have tried multiple ways of giving input to the filter query parameter, but the application throws different exceptions or does not change the response json.

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=praesentation like '%amager%'`
Does not failed with an exceptions, but where clause is not used/does not change the json response.

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=IN ('id','praesentation')`

Exception:
`java.lang.RuntimeException: Must set primary key before trying to encode FIDFilters`

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=praesentation IN ('Amager')`

Exception:
`java.lang.RuntimeException: Must set primary key before trying to encode FIDFilters`

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=postnummer > '1000'`

Exception:
`org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying > integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Where: PL/pgSQL function api.postdistrikt(text,text,integer,integer) line 75 at RETURN QUERY [statement:"select (api.postdistrikt(:q, :where, 1, :limit)).*", arguments:{positional:{}, named:{q:a,limit:10,where:postnummer > 1000}, finder:[]}]`

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=postnummer > ''1000''`

Exception:
`org.geotools.filter.text.cql2.CQLException: Encountered "1000" at line 1, column 16.
Was expecting one of:
    <EOF> 
    <AND> ...
    "or" ...
    "/" ...
    "*" ...
    "+" ...
    "-" ...
     Parsing : postnummer > ''1000''.`

Request url: `/search?q=a&token={{token}}&resources=adresse&resources=postdistrikt&filter=st_area(geometri) > 184339980`

Exception:
`org.geotools.filter.text.cql2.CQLException: Function not found. Parsing : st_area(geometri) > ''184339980''.`

A sql query that returns data in the database:
`SELECT (api.postdistrikt('lyn','postnummer > ''1000''', 1, 100)).*;`

**Comment by bjornharrtell** [comment]
Need to investigate. But at the least it seems error handling should probably be reworked to not expose internal details of failures and instead give a more generic error.

**Comment by bjornharrtell** [comment]
And at least for some of your attempts the syntax is invalid. You cannot use raw SQL as if you was in the database directly, you must use ECQL which is an extension/variant of CQL. See https://docs.geoserver.org/stable/en/user/tutorials/cql/cql_tutorial.html and https://docs.geoserver.org/stable/en/user/filter/ecql_reference.html#filter-ecql-reference.

**Comment by bjornharrtell** [comment]
@Nobralyra do you have the application deployed somewhere I can try it out?

**Comment by bjornharrtell** [comment]
Another quick observation is that filtering is not compatible with requesting multiple resources at the same time.

I would actually advice to remove the capability to request multiple resources at the same time, It was implemented for compatibility reasons but I do not think it's a good idea.

**Comment by Nobralyra** [comment]
> Need to investigate. But at the least it seems error handling should probably be reworked to not expose internal details of failures and instead give a more generic error.

The exceptions I wrote here does not come out in the response because I changed the error handling to not expose those details. It just give a 
`{
    "status": "BAD_REQUEST",
    "message": "Not allowed input",
    "errors": null
}`

Can you make an example of a URL with a filter that works?

**Comment by Nobralyra** [comment]
> Another quick observation is that filtering is not compatible with requesting multiple resources at the same time.
> 
> I would actually advice to remove the capability to request multiple resources at the same time, It was implemented for compatibility reasons but I do not think it's a good idea.

Okay that needs to be fixed. A talked with Elvis and there are requests on the old services that takes multiple resources at the same time, so I think I need to implement a check that gives an error to the client if they have requested multiple resources and have filter parameter at the same time.

**Comment by bjornharrtell** [comment]
@Nobralyra but we decided to not be backward compatible so why should we be in this case if we agree the feature is not something we want for the future? (it's bad practice because it both complicates the API contract and puts the parallelization in the wrong place - it should be in the client not server)

**Comment by Nobralyra** [comment]
The user Septima has gained access to the service and the URL is `https://api.dataforsyningen.dk/rest/gsearch/v1.0/search`.

**Comment by DocDemar** [comment]
The ability to use multiple resources at the same time is retained to meet the need for simple implementation of search across registries. At a later stage, we can implement geographical filtering across registers if it is requested by the users. For now we will implement error handling in cases when using filtering searching across multiple ressources.

**Comment by bjornharrtell** [comment]
Make sense @DocDemar.

It looks like filtering does not work as well as intended but since it has passed so long time since I implemented it I'm not sure if it has regressed or it has been this way from the start. What I recall is that I tested it against the known use cases for filtering that the old geosearch supported and I had that working. But it looks like it doesn't work with equals at this time, at least not through your deployment and that is unexpected to me. Unfortunately it's not trivial for me to investigate deeper and provide better answers at this time.

**Comment by Nobralyra** [comment]
What was your use cases for filtering you had been testing with?

The place in the code that transform the CQL to SQL and encode it to String has not change since your last commit and now:
Your last commit:
https://github.com/SDFIdk/gsearch/blob/25fb79a5479ff856f36ed7e481c80557ac27f4b7/src/main/java/dk/dataforsyningen/gsearch/Controller.java#L57

The latest commit:
https://github.com/SDFIdk/gsearch/blob/main/src/main/java/dk/dataforsyningen/gsearch/rest/Controller.java#L82

**Comment by bjornharrtell** [comment]
The old use case is this from the old docs:

![image](https://user-images.githubusercontent.com/141030/194873703-91b6e1ac-66d6-49cd-9093-5d0514f40b7f.png)

**Comment by bjornharrtell** [comment]
I would expect fx. `kommunekode IN ('0561')` or `kommunekode = '0561' ` to work against resources adresse but it does not.

The only thing that appears working now is the like operator.

I'm pretty sure I've tested the first two cases a long time ago but I'm not sure because of the long time that has passed. I need to do a deeper investigation to provide better answers.

I would do the same tests locally but I don't have a working environment anymore. Could it possibly be that characters like = and ( gets mangled by the switchboard?

**Comment by Nobralyra** [comment]
I can not get the `like` operator to work, the response is the same whether or not the filter with a like operator is present.
Example:
`/search?q=Birk&token={{token}}&resources=sogn&filter=sognenavn LIKE %amager%`
Same response as:
`/search?q=Birk&token={{token}}&resources=sogn`

The service does not come around the switchboard and behaves the same way when running it local.

It is very strange.

**Comment by bjornharrtell** [comment]
Ok, but it should not be strange - it is debuggable and testable since what it is doing is translating into sql.

**Comment by bjornharrtell** [comment]
And, since it's the same software component that does CQL filter for GeoServer it should absolutely be possible to make it work as intended.

**Comment by Nobralyra** [comment]
What was the request you had that worked as intended with the `like` operator?

**Comment by bjornharrtell** [comment]
`https://api.dataforsyningen.dk/rest/gsearch/v1.0/search?login=XXX&password=XXX&q=a&resources=adresse&filter=kommunekode%20like%20%270217%27`

**Comment by bjornharrtell** [comment]
But something is clearly wrong and needs a harder look.

**Comment by bjornharrtell** [comment]
I've spent some time on this. The problem was that the ECQL would generate wrong SQL because it was not aware of the target schema. I've come up with a fix for it in referenced pull request, see more details there. Ping @Nobralyra.
